services:
  postgres:
    container_name: library_postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=library_db
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: